#! /bin/bash

testingDirectory=/home/ssdavis/40/p7/Testing
if [ $# -ne 1 ]; then
  echo "testhw usage: testhw simulator_src_directory"
  exit
fi

cd $1
rm -f *.out *.o out*.txt &> /dev/null
rm -f *Results.txt &> /dev/null

echo -n "Scores from p7 for " >> finalResults.txt

if [ -e authors.txt ]; then
  dos2unix authors.txt
  awk {'for (i = 2; i <= NF; ++i) printf"%s ", $i'} authors.txt >> finalResults.txt
  echo -e "\n"
  awk 'NR < 3 {for (i = 2; i <= NF; ++i) printf"%s", $i; printf"\n";}' authors.txt > names.txt
  echo -e "\nNote that names should be last name, then a comma, and then first name, e.g. Davis, Sean"  >> finalResults.txt
  awk {'printf"%s ", $1'} authors.txt > addresses
else
  echo  "You need to create an authors.txt file!!!! No one will receive credit for this assignment"  >> finalResults.txt
  echo "$1@ucdavis.edu" > addresses
  finger ${PWD##*/} | awk 'NR == 1 {printf"%s,%s", $5, $4}' > names.txt
fi


echo -en "\nAddresses used: " >> finalResults.txt 

cat addresses >> finalResults.txt
echo " " >> finalResults.txt

warningScore=0
styleScore=0
designScore=0
operationsScore=0 

g++ -Wall -ansi editor.cpp -o p7.out &> makeOutput


if [ -e p7.out ]; then
  grep warning makeOutput >& warningResults.txt
  warningScore=$(cat warningResults.txt | wc -l)
  operationsScore=$( $testingDirectory/p7Tester.sh $PWD)
else
  echo "Your file does not compile." > operationsResults.txt
fi

/home/ssdavis/40/cppChecker.sh $PWD | awk '/Processing/,/Violated File Details/' > styleResults.txt

designErrors=$( $testingDirectory/p7DesignChecker.sh $PWD )
styleScore=$( awk '/Total Errors Occurs/ {printf"%d\n", 7- $6}' styleResults.txt ) 

if [[ $styleScore -lt 0 ]]; then
  styleScore=0
fi

if [[ $warningScore -eq 0 ]]; then
  echo "No warnings." > warningResults.txt
fi

if [ ! -e designResults.txt ]; then
  echo "No design errors."  >> designResults.txt
  designScore=4
else
  designScore=$(( 4 - 2 * `cat designResults.txt | wc -l` ))
fi

echo "Style: $styleScore out of 7" >> finalResults.txt
echo "Design: $designScore out of 4" >> finalResults.txt
echo "Operation: $operationsScore out of 34" >> finalResults.txt
echo "Warnings (subtracted final score down to zero): $warningScore"  >> finalResults.txt

if [ $designErrors -gt 0 ]; then
  echo "You had fatal design errors listed in designResults.txt so you will receive a zero." >> finalResults.txt
  finalScore=0
else  # no fatal design errors
  if [ $operationsScore -eq 0 ]; then
    echo "Your program did not work so you will only receive points for design." >> finalResults.txt
    finalScore=$designScore
  else  # works!
    finalScore=$(( $styleScore + $designScore + $operationsScore - $warningScore))
  fi  # if operation doesn't work
fi # if fatal design errors

if [ $finalScore -lt 0 ]; then
  finalScore=0
fi

echo "Total: $finalScore out of 45.">> finalResults.txt


#  mailx -s "ECS 40 P7 Test Results" -a designResults.txt -a styleResults.txt -a operationsResults.txt -a warningResults.txt `cat addresses` < finalResults.txt

# awk 'NR == 1 {printf"%s,", $0}' names.txt >> ../results.csv
#echo " ${1%%/}, $finalScore,$operationsScore,$styleScore,$designScore,$warningScore" >> ../results.csv
#authorCount=$(grep "@" authors.txt | wc -l)

#if [ $authorCount -gt 1 ]; then
#  awk 'NR == 2 {printf"%s,", $0}' names.txt >> ../results.csv
#  echo "${1%%/}, $finalScore,$operationsScore,$styleScore,$designScore,$warningScore" >> ../results.csv
#fi

